apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: ekscluster.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: EKSCluster
  definition:
    spec:
      name: string
      version: string
      numNodes: string
      nodeGroup:
        instanceType: string
    status:
      clusterARN: ${cluster.status.ackMetadata.ARN}
  resources:
  - name: securityGroup
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        name: cluster-security-group-${spec.name}
      spec:
        vpcID: ${clusterVPC.status.id}
  - name: clusterVPC
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: VPC
      metadata:
        name: cluster-vpc-${spec.name}
      spec:
        cidrBlock: 192.168.0.0/16
  - name: subnetAZA
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: cluster-subnet-a-${spec.name}
      spec:
        availabilityZone: us-west-2a
        cidrBlock: 192.168.0.0/18
        vpcID: ${clusterVPC.status.id}
  - name: subnetAZB
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: cluster-subnet-b-${spec.name}
      spec:
        availabilityZone: us-west-2b
        cidrBlock: 192.168.64.0/18
        vpcID: ${clusterVPC.status.id}
  - name: nodeRole
    definition:
      apiVersion: noderole.x.symphony.k8s.aws
      kind: NodeRole
      metadata:
        name: noderole
      spec:
        name: noderole
  - name: cluster
    definition:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: Cluster
      metadata:
        name: ack-cluster
      spec:
        name: ack-cluster
        roleARN: ${spec.clusterRole}
        resourcesVPCConfig:
          endpointPrivateAccess: true
          endpointPublicAccess: true
          subnetIDs:
            - ${subnetAZA.status.id}
  - name: secret
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: my-kubeconfig
      data:
        caData: ${base64(cluster.status.caData)}
        endpoint: ${cluster.status.endpoint}
  - name: nodegroup
    definition:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: Nodegroup
      metadata:
        name: cluster-nodegroup
      spec:
        name: test-nodegroup
        clusterName: ${cluster.spec.name}
        subnets:
          - ${subnetAZA.status.id}
          - ${subnetAZB.status.id}
        nodeRole: ${nodeRole.status.nodeRoleARN}
        instanceTypes: "${!spec.nodeGroup.instanceType ? ['t3.medium'] : [spec.nodeGroup.instanceType]}"
        updateConfig:
          maxUnavailable: 1
        scalingConfig:
          minSize: ${spec.numNodes}
          maxSize: ${spec.numNodes}
          desiredSize: ${spec.numNodes}