apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: clusterset.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: ClusterSet
  variables:
    spec:
      version: string
      clusterCount: int
  resources:
  - name: cluster
    type: map
    range: ${spec.numClusters}
    templateDefinition:
      apiVersion: ekscluster.x.symphony.k8s.aws
      kind: EKSCluster
      metadata:
        name: ${spec.name}
      spec:
        name: ${spec.name}
        version: ${spec.version}
        nodeCount: 10