---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS cluster'
Parameters:
  ClusterName:
    Type: String
    Description: EKS cluster name
  ClusterRole:
    Type: String
    Description: EKS cluster role Arn
  NodeRole:
    Type: String
    Description: EKS cluster node role Arn
  ClusterVersion:
    Type: String
    Default: "1.28"
    Description: EKS cluster version
  KMSKey:
    Type: String
    Description: KMS Key Arn
  IPFamily:
    Type: String
    Default: ipv4
    Description: Cluster IP Family
  ClusterSubnets:
    Type: List<String>
    Description: Cluster subnets
##  Region:
##    Type: String
##    Default: us-west-2
##    Description: Region code. Default is us-west-2.
Resources:
  ### cluster ###
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName # "mgmt"
      Version: !Ref ClusterVersion
      RoleArn: !Ref ClusterRole # "arn:aws:iam::406946685607:role/AmazonEKSClusterRole"
      ResourcesVpcConfig:
        SubnetIds: !Ref ClusterSubnets
        #- "subnet-0d87626056d3dde46"
        #- "subnet-06e405d31d077192f"
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
      KubernetesNetworkConfig:
        IpFamily: !Ref IPFamily
      AccessConfig:
        AuthenticationMode: "API"
        BootstrapClusterCreatorAdminPermissions: true
      EncryptionConfig:
        - Provider:
            KeyArn: !Ref KMSKey # "arn:aws:kms:us-west-2:406946685607:key/728dee94-2e4f-4bf1-930a-553cf95963c8"
          Resources:
            - "secrets"
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler
      Tags:
        - Key: "test"
          Value: "value"

  ### access entries ###
  EKSNodeRoleAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      ClusterName: !Ref ClusterName # !GetAtt EKSCluster.Arn
      PrincipalArn: !Ref NodeRole
      Type: "EC2_LINUX"
    DependsOn: [ EKSCluster ]

  ACKLambdaControllerPIA:
    Type: AWS::EKS::PodIdentityAssociation
    Properties:
      ClusterName: !Ref ClusterName
      RoleArn: arn:aws:iam::406946685607:role/ACKLambdaControllerIRSARole
      Namespace: ack-system
      ServiceAccount: ack-lambda-controller
    DependsOn: [ EKSCluster ]

  ### OIDC provider ###
  EKSClusterOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - "sts.amazonaws.com"
      ThumbprintList:
        - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
      Url: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
    DependsOn: [ EKSCluster ]
