apiVersion: extentions.symphony.io/v1
kind: SymphonyResourceDefinition
metadata:
  name: api-deployment-composite-resource
spec:
  apiVersion: example.symphony.io/v1
  kind: XIRSA
  definition:
    spec:
      awsAccountID: string
      eksOIDC: string
      permissionsBoundaryArn: string
      policyArns: '[]string'
      serviceAccountName: string
      resourceConfig:
        deletionPolicy: string
        region: string
        tags: map[string]string
    status:
      roleArn: string
      roleName: string
    required:
      - awsAccountID
      - eksOIDC
      - serviceAccountName
      - resourceConfig
  resources:
    - name: irsa-policy
      definition:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Role
        metadata:
          name: irsa-policy
        spec:
          name: irsa-policy
          policies: $spec.policyARNs
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::${spec.awsAccountID}:oidc-provider/${eksOIDC}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringLike": {
                      "$eksOIDC:sub": "system:serviceaccount:${metadata.namespace}:${serviceAccountName}"
                    }
                  }
                }
              ]
            }
    - name: service-account
      definition:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: $spec.serviceAccountName
          annotations:
            eks.amazonaws.com/role-arn: $irsa-policy.status.ACKResourceMetadata.ARN