# permissions for end users to view abstractions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: abstraction-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: symphony
    app.kubernetes.io/part-of: symphony
    app.kubernetes.io/managed-by: kustomize
  name: abstraction-viewer-role
rules:
- apiGroups:
  - x.symphony.k8s.aws
  resources:
  - abstractions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - x.symphony.k8s.aws
  resources:
  - abstractions/status
  verbs:
  - get
