apiVersion: x.symphony.k8s.aws/v1alpha1
kind: Abstraction
metadata:
  labels:
    app.kubernetes.io/name: abstraction
    app.kubernetes.io/instance: abstraction-sample
    app.kubernetes.io/part-of: symphony
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: symphony
  name: abstraction-sample
spec:
  # TODO(user): Add fields here
