apiVersion: x.symphony.k8s.aws/v1alpha1
kind: Construct
metadata:
  name: circular.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: Circular
  definition:
    spec:
      name: string
  resources:
  - name: a1
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: "${spec.name}"
      spec:
        name: "${a2.status.name}"
  - name: a2
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: "${spec.name}"
      spec:
        name: "${a3.status.name}"
  - name: a3
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: "${spec.name}"
      spec:
        name: "${a1.status.name}"