apiVersion: x.symphony.k8s.aws/v1alpha1
kind: Abstraction
metadata:
  name: pods3.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: PodS3
  definition:
    spec:
      podName: string
      bucketName: string
  resources:
  - name: pod
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: my-pod-with-s3
      spec:
        containers:
        - name: pod
          image: amazon/aws-cli
          command:
          - sh
          - -c
          - echo \"Primary bucket location is ${bucketPrimary.status.location}\"
          env:
          - name: SECONDARY_BUCKET_LOCATION
            value: ${bucketSecondary.status.location}
  - name: bucketPrimary
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.bucketName}
      spec:
        name: ${spec.bucketName}
  - name: bucketSecondary
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.bucketName}-secondary
      spec:
        name: ${spec.bucketName}-secondary