apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: podbucket.x.symphony.k8s.aws
spec:
  # CRD GVR
  apiVersion: v1alpha1
  kind: PodAndBuckets

  # Variables (CRD Spec/Status)
  variables:
    spec:
      namePrefix: string
      enableVersioning: boolean
      numberOfBuckets: int
    status:
      awsBucketLocation: ${awsBucket.status.location}

  # Resources
  resources:
  - name: awsBucket
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.namePrefix}-suffix
      spec:
        name: ${spec.namePrefix}-suffix
        versioning:
          status: ${spec.enableVersioning}

  - name: pod
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-with-s3-${randomString(5)}
      spec:
        containers:
        - name: pod
          image: amazon/aws-cli
          command:
          - sh
          - -c
          - echo \"AWS bucket location is ${awsBucket.status.location}\"
          env:
          - name: AWS_BUCKET_LOCATION
            value: ${awsBucket.status.location}