apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: pods3.x.symphony.k8s.aws
spec:
  kind: PodS3
  variables: # CRD Definition
    spec:
      podName: string
      bucketName: string
    status:
      bucketLocation: ${bucketPrimary.status.location}
      podReady: ${pod.conditions.exists(c, c.Ready == true)}
  resources: # Resources and their relationship
  - name: pod
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: ${spec.podName}
      spec:
        containers:
        - name: pod
          image: amazon/aws-cli
          command:
          - sh
          - -c
          - echo \"Primary bucket location is ${bucketPrimary.status.location}\"
          env:
          - name: SECONDARY_BUCKET_LOCATION
            value: ${bucketSecondary.status.location}
  - name: bucketPrimary
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.bucketName}
      spec:
        name: ${spec.bucketName}









