apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: s3.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: SecureS3

  variables: # CRD Definition
    spec:
      numBuckets: int
    status:
      location: ${secureBucket.status.location}

  resources: # Resources
  - name: secureBucket
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.name}
      spec:
        name: ${spec.name}
        acl: PRIVATE
