apiVersion: x.symphony.k8s.aws/v1alpha1
kind: Construct
metadata:
  name: simples3var.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: SimpleS3Var
  definition:
    spec:
      name: string
      crName: string
  resources:
  - name: my-var-bucket
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: "${spec.crName}"
      spec:
        name: "${spec.name}"
  - name: my-var-bucket-2
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.crName}-2
      spec:
        name: ${spec.name}-2