apiVersion: x.symphony.k8s.aws/v1alpha1
kind: Abstraction
metadata:
  name: simples3var.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: SimpleS3Var
  definition:
    spec:
      name: string
  resources:
  - name: my-var-bucket
    definition:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${spec.name}
      spec:
        name: ${spec.name}